# -*- coding: utf-8 -*-
"""homework_3_dag_np

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FybIHcueX3DhxjrDHXF4_iK_VtIP04M

## DAG file for DE300 HW3

In this file, we handle:
- Set up a DAG to produce a recommendation .

- Combine the updated observations with the previous ones.
- Generate five movie recommendations for each of the following user types:
  - Cold user: a user for whom the system has no prior interaction data.
  - Top user: a randomly selected user whose number of interactions is in the top 5% of users.
- Save the recommendations in a separate file and upload to the S3 bucket, under directory recommendations.
- Each output file should include:
  - User_Type
  - Last_Interaction_Time
  - other user summary fields you choose (e.g., number of ratings observed so far)
  - a list of the recommended movies
- Important: Use a file naming scheme that prevents overwriting outputs from earlier iterations.
"""

#### Imports --DO NOT RUN IN COLAB

from airflow import DAG
from airflow.operators.python import PythonOperator, BranchPythonOperator, PythonVirtualenvOperator
from airflow.operators.empty import EmptyOperator
import pendulum
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
import json
import boto3
import tempfile
from pathlib import Path
from threading import local

#### HELPERS

def df_to_xcom(df: pd.DataFrame) -> str:
  return df.to_json(orient="records")

def xcom_to_df(payload: str) -> pd.DataFrame:
  if not payload:
    return pd.DataFrame()
  return pd.DataFrame(json.loads(payload))


def load_movies(BUCKET, PATH):
    '''
    This function downloads the movies file from S3 and outputs it as a pandas dataframe.
    '''
    s3 = boto3.client('s3')

    # Creating the directory
    with tempfile.TemporaryDirectory() as td:

        td = Path(td)
        movies_path = td / 'movies.dat'

        # Downloading the file
        s3.download_file(BUCKET, PATH, str(movies_path))

        # Creating the dataframe
        movies = pd.read_csv(
            movies_path, sep='::', engine='python', names=['movie_id', 'title', 'genres'], encoding='latin-1'
        )

        movie_ids = movies["movie_id"].astype(int)
        id_to_row = {int(mid): i for i, mid in enumerate(movie_ids.tolist())}

    return movies, movie_ids, id_to_row


# Randomly selecting a user in the top 5%
def pick_top_user(df, seed=123):
    if df.empty:
        return None
    
    user_counts = df["user_id"].value_counts()
    if len(user_counts) == 0:
        return None

    # Computing 95th percentile cutoff
    cutoff = np.quantile(user_counts.values, 0.95)

    # Users in top 5%
    top_users = user_counts[user_counts >= cutoff].index.to_numpy()

    if len(top_users) == 0:
        return None

    rng = np.random.default_rng(seed)
    return int(rng.choice(top_users))

def format_movie_list(movie_ids, items_df):
    '''
    This function formats the movie list by joining the movie id, title, and genre
    '''

    m = items_df.set_index('movie_id')[['title', 'genres']]
    parts = []
    for mid in movie_ids:
        mid = int(mid)
        if mid in m.index:
            title = m.loc[mid, 'title']
            genres = m.loc[mid, 'genres']
            parts.append(f'{mid}: {title} [{genres}]')
        else:
            parts.append(str(mid))
    return ' | '.join(parts)

# Recommendation function for a general user

def recommend(user_id,
              events,
              E,
              item_ids,
              id_to_row,
              item_col='movie_id',
              ts_col='ts',
              topk=5,
              N=10,
              min_rating=4):
    '''
    This function creates a recommendation for the general user. It gets the N most recent events and select the ones with good rating.
    '''

    uev = (
        events[events['user_id'] == int(user_id)]
        .sort_values(ts_col, ascending=False)
        .tail(N)
    )
    uev = uev[uev['rating'] >= float(min_rating)]

    mids = [int(m) for m in uev[item_col].tolist() if int(m) in id_to_row]
    if not mids:
        return []

    rows = np.array([id_to_row[m] for m in mids], dtype=int)
    seen_rows = set(rows.tolist())

    # user profile = mean of watched embeddings
    u = E[rows].mean(axis=0)  # (d,)
    u = u / max(np.linalg.norm(u), 1e-12)

    # cosine similarity (since E is normalized)
    sims = E @ u  # (n_items,)

    # argsort desc, excluding seen
    candidates = [i for i in np.argsort(-sims) if i not in seen_rows]
    top_rows = candidates[:topk]

    return [int(item_ids[i]) for i in top_rows]


# Recommending to cold users based on popularity
def recommend_cold(events, items, k=5):
    '''
    This function creates a recommendation for cold users.
    '''

    # Select only the movie id's present on the item subset
    subset_ids = set(items['movie_id'].astype(int).tolist())

    # Creating recommendation is based on popularity
    pop = (events[events['movie_id'].isin(subset_ids)]
           ['movie_id'].value_counts().head(k).index.astype(int).tolist())
    return pop

#### TASKS
'''
offline, we handle loading data, creating embeddings, and partitioning data

with dag, we need to download embeddings, download correct partition of data, perform recommendations, and upload results to s3

in fingerson-lacombefarina-mwaa/dags/:
  - partition_1.csv
  - partition_2.csv
  - partition_3.csv
  - partition_4.csv
  - movies.dat
  - embeddings.csv
  - run_count.json
  - output/
    - recs_1.csv
    - recs_2.csv
    - recs_3.csv
    - recs_4.csv
'''

def download(**context):
    """
    Downloads the current partition(s) from S3 and uploads a single CSV file with all partitions.
    Returns the S3 key of the merged partition.
    """
    import boto3
    import tempfile
    from pathlib import Path
    import pandas as pd

    s3 = boto3.client("s3")
    bucket_name = 'fingerson-lacombefarina-mwaa'
    num_parts = 4

    # Extract run_count
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)

        run_count_path = td / "run_count.json"
        s3.download_file(bucket_name, "dags/run_count.json", str(run_count_path))
        run_count = int(run_count_path.read_text().strip())
        n_parts = min(run_count, num_parts)

        # Download partitions
        parts = []
        for i in range(1, n_parts + 1):
            local_path = td / f"partition_{i}.csv"
            s3.download_file(bucket_name, f'partition_{i}.csv', str(local_path))
            parts.append(pd.read_csv(local_path))

        if not parts:
            partition_data = pd.DataFrame()
        else:
            partition_data = pd.concat(parts, ignore_index=True)

        # Save merged partition to temp CSV
        merged_path = td / f"merged_partition_{run_count}.csv"
        partition_data.to_csv(merged_path, index=False)

        # Upload merged partition to S3
        merged_key = f"dags/tmp/merged_partition_{run_count}.csv"
        s3.upload_file(str(merged_path), bucket_name, merged_key)

    # Return only the S3 key (small string XCom)
    return merged_key

def check_run_count(**context):
    s3 = boto3.client('s3')
    bucket_name = 'fingerson-lacombefarina-mwaa'
    run_count_key = 'dags/run_count.json'

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        local_path = td / 'run_count.json'
        s3.download_file(bucket_name, run_count_key, str(local_path))
        run_count = int(local_path.read_text().strip())

    # Branch: if run_count > 4, skip downstream tasks
    if run_count > 4:
        return "stop_dag"
    else:
        return "continue_dag"

def run_recommend(**context):
  '''
  This function:
  - downloads embeddings from se
  - creates a recommendation for one cold and one top
  - creates a recommendations file
  '''

  s3 = boto3.client('s3')
  bucket_name = 'fingerson-lacombefarina-mwaa'

  # Downloading embeddings from S3
  with tempfile.TemporaryDirectory() as td:
    td = Path(td)
    emb_path = td / "full_embedding.npy"
    emb_key = "full_embedding.npy"
    s3.download_file(bucket_name, emb_key, str(emb_path))

    E = np.load(emb_path)
    norms = np.linalg.norm(E, axis=1, keepdims=True)
    E = E / np.maximum(norms, 1e-12)


#   # Grabbing data partition from download task
#   partition = xcom_to_df(context["ti"].xcom_pull(task_ids="download"))

  merged_key = context['ti'].xcom_pull(task_ids="download")
  with tempfile.TemporaryDirectory() as td:
    td = Path(td)
    local_path = td / "merged_partition.csv"
    s3.download_file(bucket_name, merged_key, str(local_path))

    # Load partition
    ratings = pd.read_csv(local_path)
    ratings['ts'] = pd.to_datetime(ratings['timestamp'], unit='s')

  # Downloading movies.dat from s3 and create item metadata
  movies, movie_ids, id_to_row = load_movies('fingerson-lacombefarina-mwaa', 'movies.dat')
  items = movies[['movie_id', 'title', 'genres']]

  # Picking top user
  # Pick top 5% user from entire dataset
  top_user = pick_top_user(ratings, seed=3)

  if top_user is None:
    print("No valid top user found.")
    return None

  print(f"Selected top user: {top_user}")

  # Creating the user counts and the number of interactions for it
  user_counts = ratings.groupby('user_id').size().rename('Num_Interactions')

  # Selecting the top 5% percentile
  top5_cutoff = int(np.quantile(user_counts.values, 0.95))

  # Extracting the last interaction time for the top user
  top_user_ratings = ratings[ratings['user_id'] == top_user]
  last_interaction_time = top_user_ratings['ts'].max()
  last_interaction_str = last_interaction_time.strftime("%Y-%m-%d %H:%M:%S")

  # Generating recommendations
  # Top user
  top_ids = recommend(
        user_id=top_user,
        events=ratings,
        E=E,
        item_ids=movie_ids,
        id_to_row=id_to_row,
        item_col='movie_id',
        ts_col='ts')

  top_user_row = {
        'User_Type': 'Top user',
        'User_ID': int(top_user),
        'Last_Interaction_Time': last_interaction_str,
        'Num_Interactions': int(user_counts.loc[top_user]),
        'Top5_Interaction_Cutoff': top5_cutoff,
        'Recommended_Movies': format_movie_list(top_ids, items),
    }

  # Cold user
  cold_ids = recommend_cold(ratings, items, k=5)

  cold_user_row = {
        'User_Type': 'Cold user',
        'User_ID': None,
        'Last_Interaction_Time': None,
        'Num_Interactions': 0,
        'Top5_Interaction_Cutoff': '',
        'Recommended_Movies': format_movie_list(cold_ids, items),
  }

  recs = pd.DataFrame([top_user_row, cold_user_row])

  return df_to_xcom(recs)


def upload(**context):
  '''
  This function:
  - uploads recommendations to s3 bucket
  s3://fingerson-lacombefarina-mwaa
  - uses use timestamp or count number to differentiate recommendation files

  '''
  # Extracting recommendations from recommend task
  recs = xcom_to_df(context["ti"].xcom_pull(task_ids="run_recommend"))

  s3 = boto3.client("s3")
  bucket_name = "fingerson-lacombefarina-mwaa"

  with tempfile.TemporaryDirectory() as td:
    td = Path(td)

    # Download run_count.json
    run_count_key = 'dags/run_count.json'
    run_count_path = td / "run_count.json"
    s3.download_file(bucket_name, run_count_key, str(run_count_path))
    run_count_obj = json.loads(run_count_path.read_text())
    run_count = int(run_count_obj)

    print(f'run_count downloaded and count is {run_count}')

    # Uploading recommendations
    recs_file = td / f"recs_{run_count}.csv"
    recs.to_csv(recs_file, index=False)
    out_key = f'dags/output/recs_{run_count}.csv'
    s3.upload_file(str(recs_file), bucket_name, out_key)
    print(f'file was uploaded to {out_key}')


def update_count(**context):
  '''
  This function:
  - uploads .json to s3 that just contains a number
  - at each run of the dag, it adds 1 to the number to keep track of the run
  '''
  s3 = boto3.client('s3')
  bucket_name = 'fingerson-lacombefarina-mwaa'
  run_count_key = 'dags/run_count.json'

  with tempfile.TemporaryDirectory() as td:
    td = Path(td)
    local_path = td/'run_count.json'

    s3.download_file(bucket_name, run_count_key, str(local_path))
    run_count = json.loads(local_path.read_text())
    run_count += 1 # increment
    local_path.write_text(json.dumps(run_count))

    s3.upload_file(str(local_path), bucket_name, run_count_key)

    print(f'Updated run_count to: {run_count}')

#### DAG

# DAG + tasks + dependencies
default_args = {
    "owner": "fingerson-lacombefarina",
    "depends_on_past": False,
    "start_date": pendulum.today("UTC").add(days=-1),
    "retries": 1,
}

WORKFLOW_SCHEDULE = pendulum.duration(hours=10)

with DAG(
    dag_id="homework_3_dag_np",
    default_args=default_args,
    description="dag file for hw3 (numpy version)",
    schedule=WORKFLOW_SCHEDULE,
    tags=["de300"],
    catchup=False,
    max_active_runs=1,
    ) as dag:


    # TASKS
    branch_task = BranchPythonOperator(
        task_id="check_run_count",
        python_callable=check_run_count,
    )

    stop_dag = EmptyOperator(task_id="stop_dag")
    continue_dag = EmptyOperator(task_id="continue_dag")

    task1 = PythonOperator(
        task_id="download",
        python_callable=download,
        )

    task2 = PythonOperator(
        task_id="run_recommend",
        python_callable=run_recommend,
        )

    task3 = PythonOperator(
        task_id="upload",
        python_callable=upload,
        )

    task4 = PythonOperator(
        task_id="update_count",
        python_callable=update_count,
    )

    

    


# Dependencies
'''
1. download the embeddings and correct data from s3
2. create recommendations
3. upload results to s3
4. update run_count.json
'''
branch_task >> continue_dag >> task1 >> task2 >> task3 >> task4
branch_task >> stop_dag
